apiVersion: v1
kind: ConfigMap
metadata:
  name: playlists-config
  namespace: bernardosilva
data:
  DATASET_VERSION: "ds2"
  DATASET_URL: "https://homepages.dcc.ufmg.br/~cunha/hosted/cloudcomp-2023s2-datasets/2023_spotify_ds2.csv"

# To update the dataset, change the URL and the version;